mqtt:
  brokerUrl: ${MQTT_BROKER_HOST}
  topic: ${MQTT_TOPIC}
  qos: ${MQTT_QOS:2}
  clientId: ${MQTT_CLIENT_ID}
  maxInflight: ${MQTT_MAX_INFLIGHT:10000}
  keepAliveIntervalSeconds: ${MQTT_KEEP_ALIVE_INTERVAL:30}
  connectionTimeoutSeconds: ${MQTT_CONNECTION_TIMEOUT_SECONDS:10}
  username: ${MQTT_BROKER_USERNAME:}
  password: ${MQTT_BROKER_PASSWORD:}

pulsar:
  serviceUrl: ${PULSAR_SERVICE_URL}
  topic: ${PULSAR_PRODUCER_TOPIC}
  sendTimeoutSeconds: ${PULSAR_SEND_TIMEOUT_SECONDS:20}
  maxPendingMessages: ${PULSAR_PRODUCER_QUEUE_SIZE:10000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
