#!/bin/bash

matches_semver() {
  # Simple regex-check, allows optionally three levels separated with .
  if [[ "$1" =~ [0-9]+(\.[0-9]+(\.[0-9]+)?)?$ ]]; then
    # 0 = true
    return 0
  else
    # 1 = false
    return 1
  fi
}

set -u

if [ -n "${TRAVIS_TAG}" ]; then
  TRAVIS_SEMVER="$(matches_semver "${TRAVIS_TAG}")"
  if [ "$?" -ne 0 ]; then
    echo "TRAVIS_TAG ${TRAVIS_TAG} does not follow semver" 1>&2
    exit 1
  fi
  PACKAGE_VERSION="$(xmllint --nsclean --xpath '/project/version/text()' pom.xml)"
  PACKAGE_SEMVER="$(matches_semver "${PACKAGE_VERSION}")"
  if [ "$?" -ne 0 ]; then
    echo "version ${PACKAGE_VERSION} in pom.xml does not follow semver" 1>&2
    exit 1
  fi
  if [ "${TRAVIS_TAG}" != "${PACKAGE_VERSION}" ]; then
    echo "According to semver, TRAVIS_TAG ${TRAVIS_TAG} differs from version ${PACKAGE_VERSION} in pom.xml" 1>&2
    exit 1
  else
    echo "Travis tag and pom.xml versions match"
  fi
fi
