#!/bin/sh

set -u

[ "$#" -ne 3 ] && {
  echo "Usage: $(basename "$0") SOURCE_IMAGE[:TAG] TARGET_IMAGE_WITHOUT_TAG TRAVIS_TAG" 1>&2
  exit 1
}

SOURCE_IMAGE_TAG="$1"
TARGET_IMAGE_WITHOUT_TAG="$2"
TAG_FROM_TRAVIS="$3"

PUSH='./.travis/docker_login_tag_push'

SEMVER_FULL="$(echo "${TAG_FROM_TRAVIS}" | sed -e 's/^[^0-9]*//')"
# semver allows no whitespace. I assume Docker image name does not either.
TARGET_IMAGES="${TARGET_IMAGE_WITHOUT_TAG}:${SEMVER_FULL}"

IS_PRE_RELEASE="$(if [ $(echo "${SEMVER_FULL}" | grep -F -c '-') -gt 0 ]; then
                    echo 'true'
                  else
                    echo 'false'
                  fi)"
if [ "${IS_PRE_RELEASE}" != true ]; then
  SEMVER_MINOR="$(echo "${SEMVER_FULL}" | tr -C -d '[:digit:].' | cut -d . -f 1-2)"
  SEMVER_MAJOR="$(echo "${SEMVER_MINOR}" | cut -d . -f 1)"
  TARGET_IMAGES="${TARGET_IMAGES} ${TARGET_IMAGE_WITHOUT_TAG}:${SEMVER_MINOR}"
  TARGET_IMAGES="${TARGET_IMAGES} ${TARGET_IMAGE_WITHOUT_TAG}:${SEMVER_MAJOR}"
fi

"${PUSH}" "${SOURCE_IMAGE_TAG}" ${TARGET_IMAGES}
