#!/bin/sh

set -u

[ "$#" -lt 2 ] && {
  echo "Usage: $(basename "$0") SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]..." 1>&2
  exit 1
}

SOURCE_IMAGE_TAG="$1"
shift 1
IS_DOCKER_HUB_AVAILABLE="$(if [ -z ${DOCKER_USERNAME+foo} ]; then
                             echo 'false'
                           else
                             echo 'true'
                           fi)"

if [ "${IS_DOCKER_HUB_AVAILABLE}" = true ]; then
  # Avoid a warning from docker login by using --password-stdin.
  echo "${DOCKER_PASSWORD}" \
    | docker login --username="${DOCKER_USERNAME}" --password-stdin
  if [ $? -ne 0 ]; then
    echo "docker login failed with exit status $?" 1>&2
    exit 1
  fi
  echo "Info: Push the following images to Docker Hub: $*" 1>&2
  for TARGET in "$@"; do
    docker tag "${SOURCE_IMAGE_TAG}" "${TARGET}"
    if [ $? -ne 0 ]; then
      echo "docker tag failed with exit status $?" 1>&2
      exit 1
    fi
    docker push "${TARGET}"
    if [ $? -ne 0 ]; then
      echo "docker push failed with exit status $?" 1>&2
      exit 1
    fi
  done
else
  echo "Info: DOCKER_USERNAME or DOCKER_PASSWORD is not set" 1>&2
fi
