name: CI/CD

on: [push, pull_request]

jobs:
  build:
    uses: HSLdevcom/transitdata-shared-workflows/.github/workflows/ci-cd-java.yml@1.0.7
    secrets: inherit
    with:
      uploadJarArtifact: true
      workingDirectory: .
      runTestsInsideDocker: true